//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Radus_ConSec
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public int EMPLOYEEID { get; set; }
        public string EMPLOYEEEMAIL { get; set; }
        public string EMPLOYEEPASSWORD { get; set; }
        public string EMPLOYEENAME { get; set; }
        public string EMPLOYEELASTNAME { get; set; }
        public System.DateTime EMPLOYEEINSERTDATE { get; set; }
        public System.DateTime EMPLOYEEEDITDATE { get; set; }
    }
}
