//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Radus_ConSec
{
    using System;
    using System.Collections.Generic;
    
    public partial class PATROLITEM
    {
        public int PATROLID { get; set; }
        public int ROUTEID { get; set; }
        public int ROUTEROW { get; set; }
    }
}
