//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Radus_ConSec
{
    using System;
    using System.Collections.Generic;
    
    public partial class PATROL
    {
        public int PATROLID { get; set; }
        public string PATROLNUM { get; set; }
        public string PATROLNAME { get; set; }
        public string PATROLDESC { get; set; }
        public System.DateTime PATROLINSERTDATE { get; set; }
        public System.DateTime PATROLEDITDATE { get; set; }
    }
}
