//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Drawing;
using System.Drawing.Imaging;
namespace Radus_ConSec
{
    using System;
    using System.Collections.Generic;
    
    public partial class QR
    {
        public int QRID { get; set; }
        public byte[] QRIMAGE { get; set; }
        public string QRDESCRIPTION { get; set; }
        public System.DateTime QRINSERTDATE { get; set; }
        public System.DateTime QREDITDATE { get; set; }
    }
}
