//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Radus_ConSec
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROUTE
    {
        public int ROUTEID { get; set; }
        public string ROUTEDESC { get; set; }
        public string ROUTENAME { get; set; }
        public byte[] ROUTEQR { get; set; }
        public System.DateTime ROUTEINSERTDATE { get; set; }
        public System.DateTime ROUTEEDITDATE { get; set; }
        public string ROUTECODE { get; set; }
    }
}
